### ISSUE TITLE
Issue Training

### ISSUE THREAD

**Issue by philliprossisyncapse** [lrvick/synt#5]
Hello,

I get the following error when trying to train synt:

(my_new_env3)prossi:Tawlk-synt-dfd2c6a prossi$ synt train 'mysamples.db' 20000 
Beginning train on mysamples.db database with 20000 samples.
Traceback (most recent call last):
  File "/Users/prossi/Documents/Tawlk-synt-dfd2c6a/my_new_env3/bin/synt", line 5, in <module>
    pkg_resources.run_script('synt==0.1.0', 'synt')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 489, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1207, in run_script
  File "/Users/prossi/Documents/Tawlk-synt-dfd2c6a/my_new_env3/lib/python2.7/site-packages/synt-0.1.0-py2.7.egg/EGG-INFO/scripts/synt", line 3, in <module>
    main()
  File "/Users/prossi/Documents/Tawlk-synt-dfd2c6a/my_new_env3/lib/python2.7/site-packages/synt-0.1.0-py2.7.egg/synt/**init**.py", line 184, in main
    redis_db        = args.redis_db, 
  File "/Users/prossi/Documents/Tawlk-synt-dfd2c6a/my_new_env3/lib/python2.7/site-packages/synt-0.1.0-py2.7.egg/synt/trainer.py", line 43, in train
    m.store_freqdists()
  File "/Users/prossi/Documents/Tawlk-synt-dfd2c6a/my_new_env3/lib/python2.7/site-packages/synt-0.1.0-py2.7.egg/synt/utils/db.py", line 125, in store_freqdists
    assert pos_words and neg_words, 'Requires wordcounts to be stored in redis.'
AssertionError: Requires wordcounts to be stored in redis.

**Comment by lrvick** [comment]
Hmm. Do you have a local Redis server up and running?

**Comment by philliprossisyncapse** [comment]
Yes I do. Is there any configuration of Redis that is required?

 (my_new_env)prossi:mohitranka-TwitterSentiment-5ad3bbe prossi$ ps -ef | grep "redis"
  502 84446   381   0   0:10.11 ttys000    0:23.16 redis-server
